// <auto-generated />
using System;
using GerenciadorTarefasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorTarefasApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424221245_CriacaoInicialEPovoamento")]
    partial class CriacaoInicialEPovoamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorTarefasApi.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Tarefas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Aprender as novidades",
                            Status = "Concluída",
                            Titulo = "Estudar .NET 10"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Criar service e componentes",
                            Status = "Pendente",
                            Titulo = "Configurar Angular"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Liberar porta 4200",
                            Status = "Concluída",
                            Titulo = "Ajustar CORS"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Organizar pastas backend e frontend",
                            Status = "Pendente",
                            Titulo = "Criar Repositório Git"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Testar GET e POST no Scalar",
                            Status = "Concluída",
                            Titulo = "Validar Endpoints"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Interfaces e Observables",
                            Status = "Pendente",
                            Titulo = "Estudar TypeScript"
                        },
                        new
                        {
                            Id = 7,
                            DataCriacao = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Aplicar CSS no Angular",
                            Status = "Pendente",
                            Titulo = "Estilizar Interface"
                        },
                        new
                        {
                            Id = 8,
                            DataCriacao = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Verificar regras de status",
                            Status = "Concluída",
                            Titulo = "Revisar Controller"
                        },
                        new
                        {
                            Id = 9,
                            DataCriacao = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Testar edição e exclusão",
                            Status = "Pendente",
                            Titulo = "Finalizar CRUD"
                        },
                        new
                        {
                            Id = 10,
                            DataCriacao = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Documentar como rodar o projeto",
                            Status = "Pendente",
                            Titulo = "Escrever README"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
